version: "3.9"

services:
  fastapi:
    build:
      context: ./backend
    container_name: audio_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  streamlit:
    build:
      context: ./frontend
    container_name: audio_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - fastapi
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: audio_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
